import { height, width } from "@/src/utils/dimensions";
import { styles } from "./styles";

export const editProfileFields = [
  {
    id: "2af107a0-af3f-4c05-bf43-add3e85f73d1",
    type: "floatingLabelInput",
    label: "strings:name",
    data: "Name",
    properties: {
      staticLabel: true,
      editable: false,
      keyboardType: "default",
      containerStyles: styles.container,
      labelStyles: styles.labelStyles,
      customLabelStyles: styles.customLabelStyles,
      inputStyles: styles.inputStyles,
    },
  },
  {
    id: "c445af89-753c-4956-b490-51b3c29a8e84",
    type: "floatingLabelInput",
    label: "strings:lbl_date_of_birth",
    data: "DOB",
    properties: {
      staticLabel: true,
      editable: false,
      keyboardType: "default",
      containerStyles: styles.container,
      labelStyles: styles.labelStyles,
      customLabelStyles: styles.customLabelStyles,
      inputStyles: styles.inputStyles,
    },
  },
  {
    id: "049f8efa-7f43-40ec-a6cf-6ce25e1012cc",
    type: "floatingLabelInput",
    label: "strings:update_aadhar_voter_id_dl_manually",
    data: "Aadhar",
    properties: {
      staticLabel: true,
      editable: false,
      keyboardType: "default",
      containerStyles: styles.container,
      labelStyles: styles.labelStyles,
      customLabelStyles: styles.customLabelStyles,
      inputStyles: styles.inputStyles,
    },
  },
  {
    id: "81f1d65a-d34b-4367-897d-e3bb83e012b5",
    type: "floatingLabelInput",
    label: "strings:pan_card",
    data: "PAN",
    properties: {
      staticLabel: true,
      editable: false,
      keyboardType: "default",
      containerStyles: styles.container,
      labelStyles: styles.labelStyles,
      customLabelStyles: styles.customLabelStyles,
      inputStyles: styles.inputStyles,
    },
  },
  {
    id: "080be0ca-e6b6-4c2d-ba4b-96e328228f0f",
    label: "strings:email",
    type: "floatingLabelInput",
    data: "EmailId",
    properties: {
      keyboardType: "email-address",
      staticLabel: true,
      containerStyles: styles.container,
      labelStyles: styles.labelStyles,
      customLabelStyles: styles.customLabelStyles,
      inputStyles: styles.inputStyles,
    },
  },
  {
    id: "85935fdc-d4ae-4648-aa53-eac776e462f2",
    type: "floatingLabelInput",
    label: "strings:alternate_contact_number",
    data: "AlternateNumber",
    properties: {
      staticLabel: true,
      maxLength: 10,
      keyboardType: "number-pad",
      containerStyles: styles.container,
      labelStyles: styles.labelStyles,
      customLabelStyles: styles.customLabelStyles,
      inputStyles: styles.inputStyles,
    },
  },
  {
    id: "32975062-9d16-46c6-b009-2e350f5e3146",
    label: "strings:lbl_current_address_mandatory",
    type: "floatingLabelInput",
    data: "AddressDetail.currentAddressDoorNo",
    properties: {
      keyboardType: "default",
      maxLength: 10,
      staticLabel: true,
      containerStyles: styles.container,
      labelStyles: styles.labelStyles,
      customLabelStyles: styles.customLabelStyles,
      inputStyles: styles.inputStyles,
    },
  },
  {
    id: "96f46ac3-c2a6-4863-86b0-bb73c5ebb6b9",
    label: "strings:lbl_current_address_line_1",
    type: "floatingLabelInput",
    data: "AddressDetail.currentAddressLine1",
    properties: {
      keyboardType: "default",
      maxLength: 128,
      staticLabel: true,
      containerStyles: styles.container,
      labelStyles: styles.labelStyles,
      customLabelStyles: styles.customLabelStyles,
      inputStyles: styles.inputStyles,
    },
  },
  {
    id: "f515df31-b3c7-4c22-be1b-955d86b0e474",
    label: "strings:lbl_current_address_line_2",
    type: "floatingLabelInput",
    data: "AddressDetail.currentAddressLine2",
    properties: {
      keyboardType: "default",
      maxLength: 60,
      staticLabel: true,
      containerStyles: styles.container,
      labelStyles: styles.labelStyles,
      customLabelStyles: styles.customLabelStyles,
      inputStyles: styles.inputStyles,
    },
  },
  {
    id: "e482c9f2-e595-4d62-a22e-45b0fcd4ed1f",
    label: "strings:lbl_current_address_line_3",
    type: "floatingLabelInput",
    data: "AddressDetail.currentAddressLine3",
    properties: {
      keyboardType: "default",
      maxLength: 60,
      staticLabel: true,
      containerStyles: styles.container,
      labelStyles: styles.labelStyles,
      customLabelStyles: styles.customLabelStyles,
      inputStyles: styles.inputStyles,
    },
  },
  {
    id: "97fbf4f6-65e2-4209-881e-664e7b64b391",
    label: "auth:newuser:Secondpagepincode",
    type: "dropDownPicker",
    data: "AddressDetail.currentPincode",
    properties: {
      mode: "BADGE",
      showBadgeDot: true,
      searchable: true,
      disableLocalSearch: true,
      searchPlaceholder: "Search Your Pincode",
      searchablePlaceholder: "Search Pincode",
      searchTextInputProps: {
        maxLength: 6,
        keyboardType: "number-pad",
      },
      listMode: "SCROLLVIEW",
      scrollViewProps: {
        nestedScrollEnabled: true,
        decelerationRate: "fast",
      },
      badgeStyle: (item: any) => ({
        padding: 5,
        backgroundColor: item.value ? "red" : "grey",
      }),
      badgeProps: {
        activeOpacity: 1.5,
      },
      badgeSeparatorStyle: {
        width: 30,
      },
      badgeColors: ["red"],
      badgeDotColors: ["red"],
      dropDownContainerStyle: {
        width: width / 1.1,
        height: height / 5,
        padding: 10,
        left: 18,
        top: 60,
        borderWidth: 0.5,
        borderTopWidth: 0,
        borderColor: "#D3D3D3",
        justifyContent: "center",
        elevation: 0,
        backgroundColor: "#D3D3D3",
      },
      style: {
        backgroundColor: "white",
        margin: 20,
        elevation: 50,
        opacity: 0.9,
        borderWidth: 0.6,
        width: width / 1.1,
        height: height / 15,
        alignSelf: "center",
        bottom: 10,
        margintop: 50,
        borderColor: "#D3D3D3",
      },
    },
  },
  {
    id: "579d9086-9d29-4ae4-8583-494b497d0af8",
    label: "strings:select_state",
    type: "floatingLabelInput",
    data: "AddressDetail.currentState",
    properties: {
      keyboardType: "default",
      staticLabel: true,
      editable: false,
      containerStyles: styles.container,
      labelStyles: styles.labelStyles,
      customLabelStyles: styles.customLabelStyles,
      inputStyles: styles.inputStyles,
    },
  },
  {
    id: "e5f652db-1c60-42cf-a990-b9e15b3b2e34",
    label: "strings:select_district",
    type: "floatingLabelInput",
    data: "AddressDetail.currentDistrict",
    properties: {
      keyboardType: "default",
      staticLabel: true,
      editable: false,
      containerStyles: styles.container,
      labelStyles: styles.labelStyles,
      customLabelStyles: styles.customLabelStyles,
      inputStyles: styles.inputStyles,
    },
  },
  {
    id: "645354b2-fc70-4b66-858c-3e852c5f9c9f ",
    label: "strings:select_city",
    type: "floatingLabelInput",
    data: "AddressDetail.currentCity",
    properties: {
      keyboardType: "default",
      staticLabel: true,
      editable: false,
      containerStyles: styles.container,
      labelStyles: styles.labelStyles,
      customLabelStyles: styles.customLabelStyles,
      inputStyles: styles.inputStyles,
    },
  },
];
